config/routes.rb
Rails.application.routes.draw do
  resources :story_books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#hello'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story_book.rb
class StoryBook < ApplicationRecord
	belongs_to :User
	validates :book_name,  presence: true
	validates :title, presence: true
	validates :Author, presence: true
	validates :genre, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :StoryBooks
	validates :first_name,  presence: true
	validates :last_name, presence: true
	validates :date_of_birth, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end

end

app/controllers/story_books_controller.rb
class StoryBooksController < ApplicationController
  before_action :set_story_book, only: [:show, :edit, :update, :destroy]

  # GET /story_books
  # GET /story_books.json
  def index
    @story_books = StoryBook.all
  end

  # GET /story_books/1
  # GET /story_books/1.json
  def show
  end

  # GET /story_books/new
  def new
    @story_book = StoryBook.new
  end

  # GET /story_books/1/edit
  def edit
  end

  # POST /story_books
  # POST /story_books.json
  def create
    @story_book = StoryBook.new(story_book_params)

    respond_to do |format|
      if @story_book.save
        format.html { redirect_to @story_book, notice: 'Story book was successfully created.' }
        format.json { render :show, status: :created, location: @story_book }
      else
        format.html { render :new }
        format.json { render json: @story_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /story_books/1
  # PATCH/PUT /story_books/1.json
  def update
    respond_to do |format|
      if @story_book.update(story_book_params)
        format.html { redirect_to @story_book, notice: 'Story book was successfully updated.' }
        format.json { render :show, status: :ok, location: @story_book }
      else
        format.html { render :edit }
        format.json { render json: @story_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_books/1
  # DELETE /story_books/1.json
  def destroy
    @story_book.destroy
    respond_to do |format|
      format.html { redirect_to story_books_url, notice: 'Story book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story_book
      @story_book = StoryBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_book_params
      params.fetch(:story_book, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/story_books_helper.rb
module StoryBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to StonnerTech.Com</title>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/story_books/_form.html.erb
<%= form_for(story_book) do |f| %>
  <% if story_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story_book.errors.count, "error") %> prohibited this story_book from being saved:</h2>

      <ul>
      <% story_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/story_books/edit.html.erb
<h1>Editing Story Book</h1>

<%= render 'form', story_book: @story_book %>

<%= link_to 'Show', @story_book %> |
<%= link_to 'Back', story_books_path %>

app/views/story_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Story Books</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @story_books.each do |story_book| %>
      <tr>
        <td><%= link_to 'Show', story_book %></td>
        <td><%= link_to 'Edit', edit_story_book_path(story_book) %></td>
        <td><%= link_to 'Destroy', story_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story Book', new_story_book_path %>

app/views/story_books/new.html.erb
<h1>New Story Book</h1>

<%= render 'form', story_book: @story_book %>

<%= link_to 'Back', story_books_path %>

app/views/story_books/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_story_book_path(@story_book) %> |
<%= link_to 'Back', story_books_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>